<?php
$x=10;
$y=5;
$sum=$x+$y;
$raz=$x-$y;
$pro=$x*$y;
$cha=$x/$y;
echo "Задание 1<br/>";
echo "$sum <br/>";
echo "$raz<br/>";
echo "$pro<br/>";
echo "$cha<br/>";
echo "Задание 2<br/>";
$x=9;
$y=1;
$sum=$x+$y;
$raz=$x-$y;
$pro=$x*$y;
$cha=$x/$y;
echo "$sum <br/>";
echo "$raz<br/>";
echo "$pro<br/>";
echo "$cha<br/>";
echo "Задание 3<br/>";
$a = 5;
$b = $a * 2;
echo "1. Исходное число a: " . $a . "<br>";
echo "Число a, увеличенное вдвое и присвоенное переменной b: " . $b."<br>";
$k = 10;
$res = ($k * 1.0 / 3) + 1;
echo "2. Исходное число k: " . $k . "<br>";
echo "Число k, уменьшенное в 3 раза и увеличенное на 1: " . $res."<br>";
$a = 5;
$area = (1/4) * $a * $a * sqrt(3);
echo "3. Площадь равностороннего треугольника со стороной длиной $a равна: " . $area."<br>";
$num1 = 10;
$num2 = 20;
$num3 = 15;
$max = max($num1, $num2, $num3); 
$min = min($num1, $num2, $num3); 
echo "4. Максимальное число из $num1, $num2, $num3: $max <br>";
echo "Минимальное число из $num1, $num2, $num3: $min";
?>